# Site settings
baseurl = "https://amusement.github.io/projects/"
languageCode = "en-us"
title = "Nafisa Shazia"
theme = "hugo-highlights-theme"
publishDir = "docs"

# Enter your tracking code to enable Google analytics
googleAnalytics = ""

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Nafisa Shazia"
  description = "A showcase of my projects and interests."

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "d3w9a@ugrad.cs.ubc.ca"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.png and overlay.png to set the background.
  backgroundpersection = true

  # Hero Section
  [params.hero]
    title = "Nafisa Shazia"
    description = "A meandering look at the projects I've been working on."
    buttontext = "Begin"

  # skill section
  [params.skill_list]
    enable = true
    title = "Interests are many."
    description = "But time is short."
    buttontext = "next"
    # the picture is storead at static/images/
    picture = "pic01.jpg"

    [[params.skills]]
      icon = "fa-puzzle-piece"
      title = "Hackathons"

    [[params.skills]]
      icon = "fa-pencil"
      title = "Reading"

    [[params.skills]]
      icon = "fa-code"
      title = "Prototyping"

    [[params.skills]]
      icon = "fa-sitemap"
      title = "Distributed Systems"

  # about section
  [params.about]
    enable = true
    title = "AWS Networking Diagnostics"
    description = "A command-line debugging tool developed for an internal hackathon at Hootsuite."
    buttontext = "next"
    # the picture is storead at static/images/
    picture = "pic02.jpg"



# infos section
  [params.infos]
    enable = true
    title = "Perfect Place For Me"
    description = "A web application developed for Hack the North 2016."
    # the picture is storead at static/images/
    picture = "pic03.jpg"

  # footer section
  # this section includes
  #
  # - the contact form
  # - social icons
  #
  # It's possible to disable the whole footer or disable only social icons or contact form

  [params.footer]
    enable = true
    title = "Get in Touch"

    # contact form
    [params.footer.contact]
      enable = true

    [params.footer.contact.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send message"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "#"

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "#"

      [[params.footer.social]]
        title = "Instagramm"
        icon = "fa-instagram"
        link = "#"

      [[params.footer.social]]
        title = "Dribbble"
        icon = "fa-dribbble"
        link = "#"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "#"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "Last updated September 2017"

      [[params.footer.copyright.notice]]
        text = "Design: [HTML5UP](//html5up.net)"

      #[[params.footer.copyright.notice]]
      #  text = "Demo Images: [Unsplash](//unsplash.com/)"
